name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
  repositories:
    - repository: CICD
      name: 'Plateforme Technologique/CICD'
      type: git
      ref: 'refs/heads/develop'

variables:
  applicationName: 'KPMG Web Inspector Discovery'
  major: 1

stages:
- stage: PreProd
  displayName: "[PreProd] Discovery - Run Web Inspector"
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: web_inspector_ppr
    displayName: "Run Web Inspector on Discovery PreProd"
    variables:
      - group: PPR Web-inspector
    steps:
    - checkout: self
      path: discovery

    - template: templates/Deploy/Steps/Start-WebInspector.yaml@CICD
      parameters:
        flowConfigPath: ../discovery/flow-dynamics-report.js
        flowEnvironment:
          DISCOVERY_URL: $(DISCOVERY_URL)
          DISCOVERY_USERNAME: (DISCOVERY_USERNAME)
          DISCOVERY_PASSWORD: $(DISCOVERY_PASSWORD)
- stage: recette
  displayName: "[Recette] Discovery - Run Web Inspector"
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: web_inspector_rec
    displayName: "Run Web Inspector on Discovery REC"
    variables:
      - group: REC Web-inspector
    steps:
    - checkout: self
      path: discovery

    - template: templates/Deploy/Steps/Start-WebInspector.yaml@CICD
      parameters:
        flowConfigPath: ../discovery/flow-dynamics-report.js
        flowEnvironment:
          DISCOVERY_URL: $(DISCOVERY_URL)
          DISCOVERY_USERNAME: (DISCOVERY_USERNAME)
          DISCOVERY_PASSWORD: $(DISCOVERY_PASSWORD)
- stage: dev
  displayName: "[Dev] Discovery - Run Web Inspector"
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: web_inspector_dev
    displayName: "Run Web Inspector on Discovery DEV"
    variables:
      - group: DEV Web-inspector
    steps:
    - checkout: self
      path: discovery

    - template: templates/Deploy/Steps/Start-WebInspector.yaml@CICD
      parameters:
        flowConfigPath: ../discovery/flow-dynamics-report.js
        flowEnvironment:
          DISCOVERY_URL: $(DISCOVERY_URL)
          DISCOVERY_USERNAME: (DISCOVERY_USERNAME)
          DISCOVERY_PASSWORD: $(DISCOVERY_PASSWORD)