node {
	stage('clone') {
	    git clone 'https://github.com/BestDevendoye/web-inspect.git'
    }
    stage('build') {
        sh 'npm install'
    }

    stage('npm run inspect') {
        sh 'npm run inspect'
    }
}
