node {
	stage('clone') {
	    git 'https://github.com/BestDevendoye/web-inspect.git'
    }
    stage('build') {
        powershell 'npm install'
    }

    stage('run') {
        powershell 'npm run inspect'
    }
}
