pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('npm version') {
            steps {
                sh 'npm version'
            }
        }
        stage('install npm dependencies') {
            steps {
                sh 'npm run inspect'
            }
        }
    }
}
